name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      DOTNET_CONFIGURATION: Release
      ARTIFACTS_PATH: ./artifacts

    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: Get version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration ${{ env.DOTNET_CONFIGURATION }} --no-restore

      - name: Test
        run: |
          dotnet test \
            --configuration ${{ env.DOTNET_CONFIGURATION }} \
            --no-build \
            --verbosity normal

      - name: Pack
        run: |
          dotnet pack \
            --configuration ${{ env.DOTNET_CONFIGURATION }} \
            --no-build \
            -p:Version=${{ steps.version.outputs.VERSION }} \
            --output ${{ env.ARTIFACTS_PATH }}

      - name: Publish to NuGet
        run: |
          dotnet nuget push ${{ env.ARTIFACTS_PATH }}/*.nupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate

      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create \
            "v${{ steps.version.outputs.VERSION }}" \
            ${{ env.ARTIFACTS_PATH }}/*.nupkg \
            --generate-notes
